// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <iostream>
#include <glog/logging.h>
#include "./job_tracker_server.h"

#define JOBTRACKERNAME "localhost"
#define JOBTRACKERPORT 9000

using namespace  ::ntu::cap;

int main(int argc, char **argv) {
  //google::InitGoogleLogging(argv[0]);

  JobTrackerServer::singleton().set_port(JOBTRACKERPORT);
  JobTrackerServer::singleton().set_thread_num(10);
  auto server_thread = JobTrackerServer::singleton().start();
  server_thread.join();
  return 0;
}
